### PR TITLE
Update webui.nim

### PR DESCRIPTION
**Pull request by wwderw**
Allowing setting kiosk mode

### CODE REVIEW

**Comment by neroist** [comment]
Why was this change made? Is there an issue with the setter syntax of the function?

**Comment by wwderw** [comment]
I was getting errors when trying to compile a project.  This change allowed it to compile on my end.

**Comment by neroist** [comment]
Thats odd, can I see the function call?

**Comment by wwderw** [comment]
mainWindow.setKiosk(true) was the one that I had tried.

**Comment by neroist** [comment]
@wwderw 

You must call the function like so:

```nim
mainWindow.kiosk = true
```

**Comment by wwderw** [comment]
Good ole skill issue.  Thanks!

**Comment by wwderw** [comment]
@hassandraga  No worries at all.  I had enough smarts to look at the nim file like I would a header, but I wasn't good enough to correctly extrapolate.  

Thanks again!

**Pull request closed without merging**
